version: '3'

services:
  lc:
    build: .

    env_file:
      - .env

    ports:
      - 8888:8888

    volumes:
      - "./app:/app"

    tty: true

    entrypoint: jupyter lab --ip=0.0.0.0 --allow-root --LabApp.token=''
